/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package input;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.io.IOException;


class AppTest {
    @Test void invoice_key_exists() throws IOException {
        App classUnderTest = new App();

        // Should exist
        String key = "380|R051K9-4|2023-01-09|RO22334455";
        assertEquals(classUnderTest.invoice_key_exists(key), true);
        
        // Doesn't exists
        key = "no_key";
        assertEquals(classUnderTest.invoice_key_exists(key), false);
    }
}
